name: Build LunarCrackTool EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read
      actions: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore CrackedLunarAccountTool.sln

    - name: Build solution
      run: msbuild CrackedLunarAccountTool.sln /p:Configuration=Release

    - name: Upload compiled EXE
      uses: actions/upload-artifact@v4
      with:
        name: CrackedLunarAccountTool
        path: '**/bin/Release/*.exe'
